source 'https://github.com/CocoaPods/Specs.git'

target 'NetworkSimple', :exclusive => true do
  pod "NetworkSimple", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "NetworkSimple", :path => "../"

  pod 'Kiwi'
  pod 'OCMock', '3.1.2'
end
