language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem i activesupport
- gem install cocoapods
- pod install --project-directory=Example
- gem i slather --no-rdoc
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild test -workspace Example/NetworkSimple.xcworkspace -scheme NetworkSimple-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick
after_success: slather
